# Pre-commit hooks configuration
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.13

default_stages: [pre-commit]

repos:
  # Ruff - Linter e formatter rápido (substituto do flake8, isort, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Linter
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
        stages: [pre-commit]

  # Black - Code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.13
        args: [ --config, pyproject.toml ]
        stages: [pre-commit]

  # MyPy - Type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - pydantic>=2.0.0
        pass_filenames: false
        args: [ --config-file, pyproject.toml, simple_rag/ ]
        stages: [pre-commit]

  # Pydocstyle - Docstring style checker
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [ tomli ]
        files: ^simple_rag/
        stages: [pre-commit]

  # Hooks úteis adicionais
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ --maxkb=1000 ]
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: [ --fix=lf ]
